Yoshi275/kampongjio

- index.js
- package-lock.json
- src/App.js
Added a new App.js and a src folder
> feat: add new title

- index.js
- src/components/JioInformation/HeaderSection.js
- src/components/JioInformation/JioInfo.js
- src/components/MainPage/JioDetails.js
- src/components/common/InfoDisplay.js
- src/components/common/index.js
- src/screens/JioInformation.js
- src/screens/MainPage.js
- Created a JioInformation screen, created a new common component InfoDisplay
- JioInformation screen consisted of foundational components such as HeaderSection and JioInfo which are formatted such that it can be easily hooked up to a database. Admittedly, styling can be improved and researched more about (see below on clean-ups)
- InfoDisplay is a common component which has a static description (eg. promo code) and a dynamic answer based on data base (eg FRESH20, NEW5, etc based on the jio) and can be reused
- Some possible clean ups for front end:
// Create a master Styles list 
// Consider creating a js file for timeContainer section
// Figure out how to do something like style inheritance or overriding esp for texts in timeContainer section
A new screen for barebones implementation …
> feat: add jioinformation screen

- index.js
> fix: index.js to direct to MainPage

- index.js
- src/components/common/BigInput.js
- src/components/common/index.js
- src/screens/JioJoinerOrder.js
- Created JioJoinerOrder
- Created and use a common BigInput component
> feat: create jiojoinerorder screen

- index.js
- src/components/MainPage/JioDetails.js
- src/screens/JioInformation.js
- src/screens/Router.js
Added navigation logic from JioInformation.js to JioJoinerOrder.js page
Wired up button 'Add Jio' to navigate into JioJoinerOrder
> feat: Add jiojoinerorder nav

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/JioInformation/FullJioDetails.js
- src/components/MainPage/JioList.js
- src/components/common/CardSection.js
- src/components/common/TimeOrange.js
- src/components/common/index.js
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
Created Coordinator Screen and a common styling component, TimeOrange
- Created Coordinator Screen which is where the coordinator toggles the status of the jio, and where the order has been paid or completed.
- Created a common component TimeOrange, which is a styling to display time jio opens and closes, and time of arrival
- Encountered problem in ScrollView in JioList as it does not allow scrolling. Will fix it next time
(I forgot again)
> feat: created coordinator screen

- package-lock.json
- package.json
- src/App.js
- src/components/JioInformation/FullJioDetails.js
- src/components/MainPage/JioDetails.js
- src/data/AllJios.json
- src/data/jio-states.js
Sketched out database structure using local database `AllJios.json`
Initialised Firebase to attempt to collect data from Firebase and send data back
Venny really wants me to fix together a database.
Can move from hardcoding to dynamically rendering the components, with parent and child props.
> feat: Add local database

- src/App.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/config.js
Barebones of taking order from firebase database and reading into the application
Added config.js to 'src' to access database.
To access database, import { db } from config.js and query info accordingly.
Example of info fetching done in JioDetails
Ideally JioInformation should in future collect all orders info, then dynamically render a JioDetails component for each order.
> Add firebase database

- index.js
- package-lock.json
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/data/AllJios.json
- src/screens/JioJoinerOrder.js
- Used local json file, able to use map to create multiple corresponding jiodetails
- When using firebase, it was achievable when I created multiple states to hold the corresponding orders (order1, order2, etc) and pass it on as corresponding props in each JioDetails. This method is very static and hard coded. (see image and screenshot)
- Thus, tested with local json file and the map method we learnt from Udemy works! With changes in the json file. Essentially, json file was not well done. It should involve the use [ ] brackets as well, and while naming "order1", "order2" is easier for the human to categorise, it does not allow mapping function to take place/function properly. Thus, suggestion is to create an "id" : "order1" inside the order 1 itself. 
- One quick way to understand how …
> Refactor input processing

- src/components/MainPage/JioList.js
Edited firebase based on comments from #14. Refactored the rendering of jios into using the firebase database.
- firebase database has been edited to use [] instead of {}. 
- JioList has been modified to read the hardcoded states from firebase rather than the local database
- in future iterations, firebase will follow local `AllJios.json` files religiously
- Currently, the orders are still hardcoded. If we were to add any new orders, a new state has to be created, and passed accordingly. Can we create a for-loop with `this.state.allOrders` that dynamically renders `JioDetails order={order}` based on the state? It also seems ridiculous that the state object does not go beyond two levels of objects, which is so stupid.
- How do we display future Jios that are added? This is a pretty big …
> feat: Connect JioList to firebase

- src/data/AllJios.json
Edit the local.json foodOrders from {} to []
> feat: Change local.json foodOrders []

- src/components/JioInformation/FullJioDetails.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/screens/JioInformation.js
- src/screens/JioJoinerOrder.js
Basically passed props from JioDetails component => JioInformation screen => FullJioDetails component so all firebase info should be passed.
Added comments on things to fix:
- need to figure out reading State in JSON files, or choose not to use state constants at all (jio-states.js)
- menu link gets cut off. can we fix this? @vennylewis 
- potentially get the actual font we want to show up?
Updated Jio Page (using order3)
> feat: Update FullJioDetails with Firebase info

- src/components/MainPage/JioList.js
- src/screens/JioInformation.js
- src/screens/JioJoinerOrder.js
JioJoinerOrder now adds to firebase (see screenshot)
- JioJoinerOrder adds (temporarily) hardcoded data to firebase database, in the foodOrders
- Upon success, it navigates back to the Main Page. Is there some way we can indicate successful jio order add? Or maybe we can return to the dashboard for them to follow up and pay
- Potentially, need to find a way to track length of foodOrders array and change orderNo in the posted info
- Potentially, need to add a users list to the database too, to keep track of their names and return em under joinerName
- Presently, firebase data posted comes with its own ID. Do we want to use those? How do we access these? Need to look into it. I'm sure there's a way.
Firebase accesses arrays weirdly so foodOrders[1] would be accessible using '/foodOrders/1/' …
> feat: JioJoinerOrder adds to firebase

- src/screens/JioJoinerOrder.js
- src/screens/MainPage.js
- src/screens/Router.js
Basically added navigation from '+ Jio' in Main Page to CoordinatorCreateJio
CoordinatorCreateJio page for reference
> feat: Nav 'Create Jio' to CoordinatorCreateJio

- src/data/AllJios.json
- src/screens/CoordinatorCreateJio.js
- src/screens/JioJoinerOrder.js
Very similar to #19, with similar issues. But essentially the info can now be accessed from database as per the screenshot, after being added
- Potentially, we need to generate userdetails from their login, so that's something pretty big
- orderId should be dynamically rendered based on counting number of orders
- may want to change firebase and localJSON to not use arrays, but firebase alphanumerics (see screenshot), somehow. Then need to change MainPage to take in the info from firebase in that new way
- IMPORTANT: still need to dynamically render all orders onto the main page for it to actually show up on the app. Otherwise, it just doesn't show even though firebase is updated
- Future testing needed: Display new jio in the main page, then check if we need to rerender from firebase …
> feat: Create Jio now adds to Firebase database

- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/Initiated.js
- src/components/common/NavBar.js
- src/screens/Router.js
Navbar now links directly to the homepage and dashboard page. When other pages are made, navbar will be more fully functioning.
> Link dashboard navbar

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/MainPage/JioDetails.js
- src/screens/Coordinator.js
- src/screens/Router.js
Pass props from dashboard to coordinator, such that jios from 'Initiated Jios' direct to the coordinator page.
Potential changes:
- need to change food orders based on the individual jio food orders. Presently, it's all still hardcoded in.
Dynamically rendered food jios
> Link Dashboard to Coordinator page

- index.js
- package-lock.json
- package.json
- src/components/JioInformation/FullJioDetails.js
- src/screens/Front.js
- src/screens/JioJoinerOrder.js
- src/screens/Router.js
> add frontscreen

- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/screens/Router.js
Able to dynamically render to reflect additions in Firebase
Replaced ScrollView on map in JioList and Dashboard's PreviousDetails, OngoingDetails and InitiatedDetails. Use FlatList instead where its renderItems as a mandatory props is directed to an external function renderJio(order) to create JioDetails based on how many jios we have in Firebase. The data accepted can only be array and thus Object.values() is used to change the firebase data to array.
> Dynamic rendering through flat list and Object.values()

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/Dashboard.js
- src/screens/Router.js
Fixed the issue that InitiatedJio is not redirected to Coordinator page. Dynamically render orders from those who join jio in the Coordinator page
Potential problem: some foodChoices by certain users are initially hardcoded in arrays, however when we start creating jios and adding orders through the app, it is not saved as array. NEED to decide which way to store this. Regarding this, might need to consider whether we want the user keying in their orders to be more specific than simply a text input, in order to have standardised form of order writing, such as number of portions, price of individual item etc. This is so that a calculator function can also be integrated more seamlessly.
Warning of no key for each prop: in FlatList, this should have been handled by keyExtractor prop, and was …
> Coordinator page is dynamically rendered

- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/Ongoing.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/MainPage/JioList.js
- src/data/AllJios.json
- src/screens/CoordinatorCreateJio.js
- src/screens/JioJoinerOrder.js
Refactored the database locally, and fixed a ton of bugs and errors. Look at detailed Description below.
https://github.com/Yoshi275/kampongjio/commit/80b6152390e72c9dbc5646fa73ff8125aa13b022 AND https://github.com/Yoshi275/kampongjio/commit/aac432215cdd5216efa88088d304e6b390ea6b7d - Refactored FlatList methods to render items, and fixed the unique key for each child error discussed in #32 
https://github.com/Yoshi275/kampongjio/commit/484b2d4a1007291abf106a9c346656588ea83f25 AND https://github.com/Yoshi275/kampongjio/pull/33/commits/dc400c259dc2301562c5e7b5d2afef48a426e9e0 - Modified the local JSON and firebase to include the hasPaid and hasCollected booleans, which dynamically render in the Coordinator management page. Presently, the switch doesn't change the state on firebase. This …
> Modify base json

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/JioInformation.js
- src/screens/JioJoinerOrder.js
hasPaid and hasCollected on Firebase can now be updated from the Coordinator management page. Logic lies in the `OrderDetails` component.
hasPaid and hasCollected on `kampongjio/allOrders/$jioOrderId/foodOrders/$jioJoinOrderId/` are now updated using Firebase's `update()` rather than `push()` function
Resolve #35 
Checked Firebase while updating with switches
Switch Status on Tim Ho Wan
Updated Database
> feat: Update hasPaid and hasCollected on firebase with switch

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/JioInformation/FullJioDetails.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/data/AllJios.json
- src/data/jio-states.js
- src/data/jioStatus.js
- src/resources/icons/index.js
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/Router.js
Buttons when pressed now changes the states in Firebase. Also modularise a bit by rendering images and text according to state changes through importing helper functions. Clean up the filter functions in main page as well as dashboard.
Something else to iron out tho (see image): the jio Status in Coordinator page do not update directly even though the button was pressed (for example, when pressing the FOOD ARRIVED to change to COMPLETE JIO, the status is still Closed instead of Arrived). However, if exit and returned it will be accurate. 
Resolve #35
Resolve #35
> Buttons and states

- src/components/common/Input.js
- src/components/common/NavBar.js
- src/components/common/Spinner.js
- src/components/common/index.js
- src/config.js
- src/screens/JioJoinerOrder.js
- src/screens/LoginForm.js
- src/screens/Router.js
Added front end and logic for authentication of User, with new common component `Spinner`. This replaces the loading page.
To be done after: 
- Pass UserId around, and get information from it. Pass this into the mainpage to be passed around when needed.
- Redesign login page, add in signup form
Create login that was badly needed
Appears in Firebase authentication page.
Login Page
> feat: Add Login Form design

- src/components/common/NavBar.js
- src/resources/icons/index.js
- src/screens/LoginForm.js
- src/screens/Profile.js
- src/screens/Router.js
Despite the branch name, this is a new feature, ie. Profile Page. Displays the user's details, and should ideally be linked to a Settings page
> Profile Page

- src/components/common/Input.js
- src/screens/Front.js
- src/screens/Profile.js
- src/screens/Router.js
- src/screens/SignUp.js
Created a sign up page, with corresponding text inputs. 
Have not set up the logic and how to handleSubmit() 
Figure out an upload image feature, depending on how it will be stored in Firebase (url, or engage in a separate website)
I forgot to screenshot, sorry!
> feat: sign up page

- src/components/common/Spinner.js
- src/data/AllJios.json
- src/screens/LoginForm.js
- src/screens/MainPage.js
Following up on the login page and login creation, now we're storing user data. This is scary and problematic.
> feat: Add user database with authentication

- src/screens/LoginForm.js
Sign up previously wasn't working well, and now it's fixed, hopefully. Database is only pushed to if it's signing up for a new account that's not in the authentications user list.
Related Broken PR: #42 
Ran on database and react native app.
> fix: Fix user signup

- src/components/common/NavBar.js
- src/data/AllJios.json
- src/screens/LoginForm.js
- src/screens/MainPage.js
- src/screens/Profile.js
User login is now working, and the info is passed to the profile page!
It looks good!!!
Profile Page
> feat: Pass user login to profile page

- src/components/Dashboard/PreviousDetails.js
- src/screens/LoginForm.js
Sign Up page now sends to database well!!! But this is done using the Login => Signup flow and not the Sign Up form yet.
This allows us to read properly from the user `firebase.auth().currentUser` property :D
> fix: Sign Up Page pushes to firebase correctly

- src/screens/LoginForm.js
- src/screens/MainPage.js
- src/screens/Profile.js
- src/screens/SignUp.js
Now both Login (when email does not exist) and Signup form both signup for database.
Sign Up passes all information except `photoURL` into the profile page, and other parts, using the property `currentUser` on firebase.
Allow users to properly sign up.
Tested adding users and how it displays on firebase
Sign Up => Database + Authentication works!
> feat: Link signup to firebase

- src/components/common/Input.js
- src/screens/LoginForm.js
- src/screens/SignUp.js
Restyled login page
Have a sign up section and authentication error message. Styling follows the user profile style
> style: restyling login page

- src/App.js
- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/components/common/NavBar.js
- src/data/AllJios.json
- src/screens/Dashboard.js
- src/screens/JioJoinerOrder.js
- src/screens/LoginForm.js
- src/screens/MainPage.js
- src/screens/Profile.js
Now that login has been successfully implemented onto Firebase, Jios shown on dashboard are now customised to the User, such that it's only jios they're involved in.
Initiated Jios: coordinatorName === displayName, everything not completed
Ongoing Jios: joinerName === displayName, everything not completed
Previous Jios: either coordinator or joiner, completed
Will link to username instead of name instead, because username is more unique. Otherwise one 'Cheryl' can see all other 'Cheryl's jios.
Tested with Firebase, presently the adding of Jios and JioOrders won't correspond as names are hard-coded. Will be changed in future PR.
Venny's Filter
Cheryl's Filter
> fix: Filter Jios finally working

- src/components/MainPage/JioDetails.js
- src/components/MainPage/JioList.js
- src/screens/CoordinatorCreateJio.js
- src/screens/JioInformation.js
- src/screens/JioJoinerOrder.js
- src/screens/MainPage.js
`coordinatorCreateJio` and `jioJoinerOrder` now have names and phone numbers generated from the user login, rather than as previously (hardcoded)
> feat: Link user information to coordinatorCreateJio and jioJoinerOrder

- package-lock.json
- package.json
- src/screens/Profile.js
- src/screens/Router.js
- src/screens/SignUp.js
Download image uploading to firebase dependencies and able to render image
> Store image url

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/DashboardJioDetails.js
- src/components/JioInformation/FullJioDetails.js
- src/components/common/TimeOrange.js
- src/screens/Coordinator.js
- src/screens/CoordinatorEditJio.js
- src/screens/JioInformation.js
- src/screens/JioJoinerEditOrder.js
- src/screens/Profile.js
- src/screens/Router.js
Created a page for booth coordinator and jiojoiners to edit order. The former is access through Coordinator, whereas the latter, from Ongoing. Removed Paid and Collected Switches for the order submitted by the coordinator himself. 
The page works when accessed by Coordinator. Do not know how to get the orderDetails as props and accessed from Ongoing. HELP
> feat: EditOrder page

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/MainPage/JioDetails.js
- src/screens/CoordinatorEditJio.js
Linked the previously designed front end for `CoordinatorEditJio` (in #53) to update the jio information in firebase.
Primarily discovered a new bug, regarding how information was being passed, such that the jioOrderIds in the Initiated Jios are wrong. This is likely the case for all the ongoing and past jios too, and will be fixed in a future PR. The bug was fixed in https://github.com/Yoshi275/kampongjio/commit/707bf467441125bd2c6663f4117ce0aec0ba87cf
Also passed more necessary props into the coordinatorEditJio form, like the user information from `firebase.auth()` in https://github.com/Yoshi275/kampongjio/commit/6916791113bbbbb2b85286b115bbbbbd7f0773b5.
Do take note that in future updates, the user id should usually be retrieved, along with all other user data, that's tagged along to …
> feat: Link coordinatorEditJio to update firebase jio information

- src/components/Coordinator/OrderDetails.js
- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/screens/JioJoinerEditOrder.js
User can now edit and delete their jio orders and this updates on firebase.
https://github.com/Yoshi275/kampongjio/commit/3fa194ba7586dd2942a626028e2b65d47440abf2: Passed the props needed for the coordinator to change their own order, and got the coordinator edit food order function working. However, jio order for the regular user from `Ongoing` was still broken. This means that the `jioJoinerEditOrder` is now working, provided the right props are passed.
https://github.com/Yoshi275/kampongjio/commit/1fd0c67b745c3dd0e18cdcb5e4d33cc08a805bdc: Struggled to find the relevant props to pass from Ongoing, because previously it did not handle any foodOrder information, so now it needs to compare the foodOrder's display name to the user name, and if it's equal, then to pass the key and value to …
> feat: User jioEdit updates and deletes Firebase

- src/components/JioInformation/FullJioDetails.js
Fixed the text cut off bug. Now the title wraps around pretty nicely.
Resolve #58
> fix: Fix text cutoff of jioFullInformation

- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/screens/CoordinatorEditJio.js
- src/screens/JioJoinerEditOrder.js
- src/screens/JioJoinerOrder.js
The long-awaited bug fix of the dashboard not rendering when you scroll away has finally been fixed.
Wow I actually thought it was a larger issue than this. The main problem was that `setState` is asynchronous, so you have to do a `.then` style thing for all functions performed after, as a second parameter to the function (refer to https://medium.com/@wereHamster/beware-react-setstate-is-asynchronous-ce87ef1a9cf3)
Tackles the rendering issue that made debugging really painful because you had to log out and log in again.
Ran on one account, and changed information. This reflected on dashboard immediately :D
> MAJOR fix: Fixed Dashboard to update on change

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderDetails.js
- src/components/Coordinator/OrderList.js
- src/components/JioInformation/FullJioDetails.js
- src/data/AllJios.json
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/JioJoinerOrder.js
Calculates the price each person must pay based on deliveryCosts, discount and price for each order. Price is shown in Coordinator. Will make it such that it shows in Ongoing perhaps.
Rewrote JSON file to include minOrder and discount. jioInformation has also been updated accordingly Coordinator's order, will have hasPaid and hasCollected to be true, by default.
> Feat: Auto calc

- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/JioInformation/FullJioDetails.js
- src/data/AllJios.json
- src/screens/Coordinator.js
- src/screens/CoordinatorEditJio.js
- src/screens/JioInformation.js
- src/screens/JioJoinerEditOrder.js
- src/screens/JioJoinerOrder.js
Added a section of user's order as a jioJoiner in the JioInfo section, which they access through Dashboard's PreviousDetails and OngoingDetails.
Additionally, rewrote json file, with 1 element in each foodChoice. Edit Orders are now accessed through this new page, instead of directly from Ongoing or Previous Details
> Feat: Jio info orders

- src/components/Coordinator/OrderDetails.js
- src/screens/JioInformation.js
Now show special requests in orders, both through Coordinator page and JioInformation accessed through Dashboard
> feat: show special requests in orders

- src/components/common/Spinner.js
- src/screens/LoginForm.js
> fix: styling for spinner

- src/screens/JioJoinerOrder.js
Resolved the bug by adding a lifecycle method.
Resolve #65
> fix: jioAddOrder crash finally fixed

- src/screens/SignUp.js
Tackled the problematic error alert message on sign up for compulsory fields. Now only triggers when submit button is pressed.
Has to be a function triggering the function at `onPress`, not the function itself directly.
Resolve #70
> fix: Fix compulsory input alert in sign up

- src/components/JioInformation/FullJioDetails.js
- src/components/MainPage/JioDetails.js
- src/screens/CoordinatorCreateJio.js
- src/screens/JioInformation.js
When coordinator creates jio, they can now upload an image of the store. This will be uploaded to Firebase storage, and render as the image for the jioDetails and jioInformation pages.
https://github.com/Yoshi275/kampongjio/commit/bed7d1192d0debc3d2832e5f02231d32368819d1: Ugly styling for ImagePicker in `coordinatorCreateJio`
https://github.com/Yoshi275/kampongjio/commit/63928b07dd7113077ce5d5fe3b7e4db80a0b67e2: ImagePicker now sends information to Firebase Storage
https://github.com/Yoshi275/kampongjio/commit/07d5a8de8879d647097283da863117e7986923de: jioDetails loads the image, and `Food` icon as a default otherwise.
https://github.com/Yoshi275/kampongjio/commit/078d172dd014f1e0d5fd909e8c0c1af5cb613855: jioInformation, the full page, also loads the image if available. Default remains the …
> feat: Upload and see Store image instead of default restaurant icon

- src/components/Dashboard/DashboardJioDetails.js
- src/components/MainPage/JioDetails.js
- src/data/AllJios.json
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/JioInformation.js
- src/screens/LoginForm.js
- src/screens/MainPage.js
- src/screens/Profile.js
- src/screens/SignUp.js
Coordinator to upload receipt after order has been closed in order to proceed to indicate food has arrived. Made upload styling better
Logic in coordinator is not fully there yet, and submit buttons and how it links to database
JioInformation did not render the receipt yet as well, because logic for that is kinda not there, and the image as well. 
Remember to render the restaurant image in DashboardJioDetails as well
> Feat: Receipt feature

- package-lock.json
- src/components/Dashboard/DashboardJioDetails.js
- src/components/MainPage/JioDetails.js
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
Restaurant images show for all JioDetails and full pages in dashboard now.
Tackles bug found in #72 
Run emulator
> fix: Restaurant image appears for all dashboard restaurants if avail

- src/components/Coordinator/OrderDetails.js
- src/components/Dashboard/DashboardJioDetails.js
- src/components/Dashboard/Ongoing.js
- src/components/Dashboard/Previous.js
- src/components/MainPage/JioDetails.js
- src/components/common/Card.js
- src/components/common/CardSection.js
- src/components/common/Input.js
- src/components/common/NavBar.js
- src/components/common/Spinner.js
- src/data/AllJios.json
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/CoordinatorEditJio.js
- src/screens/JioInformation.js
- src/screens/JioJoinerEditOrder.js
- src/screens/JioJoinerOrder.js
- src/screens/Profile.js
Restyled. Remove some border lines etc
> fix: restyle dashboard and coordinator

- src/data/AllJios.json
- src/screens/Coordinator.js
- src/screens/CoordinatorCreateJio.js
- src/screens/CoordinatorEditJio.js
- src/screens/JioInformation.js
Added image styling such that the receipt renders in `JioInformation`
Ran on react-native emulator
> feat: Add receipt logic to coordinator and jioInformation

- src/screens/Profile.js
Add logout functionality to Profile
Logged out and goes back to the login form.
> feat: Add Logout logic

- src/components/Coordinator/OrderList.js
- src/screens/JioInformation.js
The dashboard will no longer crash 
Resolve #73
> fix: Fix empty food order crash

- src/screens/CoordinatorCreateJio.js
Coordinator creating a jio no longer has to upload a restaurant image.
> fix: Make restaurant image upload optional

- src/components/Coordinator/CoordinatorFullJio.js
- src/components/Coordinator/OrderList.js
- src/components/Dashboard/InitiatedDetails.js
- src/components/Dashboard/OngoingDetails.js
- src/components/Dashboard/PreviousDetails.js
- src/components/common/Button.js
- src/components/common/Spinner.js
- src/screens/Coordinator.js
Fixed Dashboard Bug, add alerts, upload button
Resolve #75
> Feat: Make restaurant image upload optional
